code/client/libmumblelink.c

Similar to one of the changes by Tim Angus in fd986da: mbstowcs' third
argument is the number of wchar_t available in dest, not the number
of bytes.
This does not appear to be exploitable, because ioquake3 does
not actually call mumble_set_identity() or mumble_set_description()
anywhere, but it might be relevant to derivatives.
Spotted via compiler warnings.

Ensure that mbstowcs does not overflow its buffer

---

README.md
code/qcommon/cvar.c

Based on cvarlist command, it only lists modified cvars.
Allows filtering like cvarlist, so `cvar_modified r*` will list modified renderer cvars.

Add cvar_modified command

---

Makefile
code/qcommon/unzip.c

unzip.[ch] and ioapi.[ch] are available as a system library on Debian, Ubuntu, Fedora.
While looking at the relevant section of the Makefile I noticed that I hadn't added support for libjpeg.pc because IJG libjpeg doesn't have it; but libjpeg-turbo does.

Enhancements for system libraries

---

Makefile

I am running Cygwin 32-bit. Make was unable to find the CC command, because the Make file was not looking for the correct location. GCC is installed on my setup as  /usr/bin/i686-pc-mingw32-gcc.
So I added the appropriate prefix to the Make file to allow building.
After this change, everything compiles fine.

Add mingw prefix for cygwin32 and mingw32

---

code/tools/lcc/cpp/unix.c

Fix for:
MSVCRT.lib(MSVCR100.dll) : error LNK2005: _memmove already defined in unix.obj
fatal error LNK1169: one or more multiply defined symbols found

No unix memmove for MSVC

---

code/qcommon/q_shared.c

strcpy() arguments may not overlap !

fix a stupid use of strcpy()

---

Makefile
code/qcommon/q_platform.h

[As with GNU/kFreeBSD, it's treated as "Linux": all three use the GNU libc
and runtime linker, which is mostly what matters for ioquake3. -smcv]
Bug-Debian: http://bugs.debian.org/679330
Reviewed-by: Simon McVittie <smcv@debian.org>

Add support for the GNU/Hurd architecture

---

Makefile
code/qcommon/q_platform.h

ioquake3 currently requires trivial code changes every time Linux developers get interested in running it on a new CPU, most recently #128 for ARM64 (aka aarch64). For the vast majority of CPUs,  the only change is to add ARCH_STRING detection, which must be kept in sync with the ARCH from the Makefile (which is just `uname -m`, with one special case for the 32-bit x86 family).
This branch passes the ARCH from the Makefile directly to q_platform.h on Linux and other GNU platforms, making it unnecessary to change anything to support new CPUs in most cases. Code changes should now only be needed if the new CPU is relevant to non-GNU platforms (Windows, OS X, *BSD), if there is genuinely something weird and assumption-breaking about it, or if someone contributes a JIT to replace the …

Implement Linux architecture support generically

---

Makefile

If TERM is not set (which can happen in autobuilders and other
batch environments), or if tput cannot determine the number of
columns for some other reason, then it can fail and not produce
any output. Prior to this change, that would result in passing
field width -4 to fmt, which is an error and causes fmt to
produce no output.

build: if tput fails, fall back to a reasonable text width

---

code/sys/sys_unix.c

The default fopen behaviour is fully-buffered I/O, which causes blocks of BUFSIZ (4KiB typically) to be read in while fread'ing. This change makes sure only the actual amount of bytes we need from /dev/urandom are read from the stream, to avoid wasting entropy.
Upstream: JACoders/OpenJK@de6a9dfd40065ae9a5a2b0b3ef701feee8dac867

Ensure reads from /dev/urandom are unbuffered

---

code/qcommon/cvar.c

Ensures functions that want to know about changes to certain types of cvars are notified that one of their cvars have been unset.
i.e. doing `/unset myvar` on a `CVAR_USERINFO|CVAR_USER_CREATED` cvar 'myvar' will let `CL_CheckUserinfo()` know that there's been a change and will send a new `userinfo` command to the server without 'myvar' in it.
Upstream: JACoders/OpenJK@9a5e9e87ff2d1302261978fa3f1adafb851bd6d6

Fix Cvar_Unset not notifying cvar_modifiedFlags

---

Makefile
code/client/cl_curl.h
code/client/cl_main.c
code/client/qal.h
code/client/snd_mix.c
code/client/snd_openal.c
code/qcommon/files.c
code/qcommon/net_ip.c
code/qcommon/q_platform.h
code/qcommon/qcommon.h
code/renderergl1/tr_shade.c
code/renderergl1/tr_shade_calc.c
code/renderergl1/tr_surface.c
code/renderergl2/tr_shade.c
code/renderergl2/tr_shade_calc.c
code/renderergl2/tr_surface.c
code/sdl/sdl_input.c
code/sys/sys_local.h
code/sys/sys_main.c
code/sys/sys_osx.m
code/sys/sys_unix.c
code/tools/lcc/cpp/unix.c

* Fix Makefile for OSX
* Bump base SDK from 10.5 -> 10.7
* Just use the builtin `__APPLE__`
---
Previously compiling on a 64 bit OSX resulted in a 32bit builds (which breaks freetype builds).
Base SDK version to 10.7 results in significantly faster binaries, plus 10.5 is ancient. More importantly, this was necessary for building with various sanitizers (e.g., `-fsanitize=address`).

Fix Makefile for OSX

---

code/qcommon/msg.c

The dead had undefined behaviour when shifting by negative amounts.
Also made the formatting of ambient code more consistent.

[qcommon/msg.c] Remove dead code

---

code/botlib/l_precomp.c

See also @TTimo's corresponding fix in BSPC: https://github.com/TTimo/bspc/commit/2c8407838398608cb9c52abae046987bb7a39c08
@timangus: For your consideration.

[code/botlib/l_precomp.c] Fix string buffer overflow

---

code/botlib/aasfile.h
code/botlib/be_aas_cluster.c
code/qcommon/cm_trace.c
code/qcommon/common.c

Found by Debian's Lintian tool.

Fix mis-spellings of "separating" as "seperating"

---

Makefile
code/game/g_main.c
code/qcommon/common.c
code/qcommon/q_shared.h
code/sys/sys_main.c

The goal of reproducible builds is that a rebuild of the same source
code with the same compiler, libraries, etc. should result in the same
binaries. SOURCE_DATE_EPOCH provides a standard way for build systems
to fill in the date of the latest source change, typically from a git
commit or from metadata like the debian/changelog in Debian packages.
This does not change anything if SOURCE_DATE_EPOCH is not defined;
the intention is that a larger build system like a Debian package
will define it.
Please see https://reproducible-builds.org/ for more information about
reproducible builds.
---
This has been used successfully in Debian, for example in <https://buildd.debian.org/status/fetch.php?pkg=ioquake3&arch=arm64&ver=1.36%2Bu20160914%2Bdfsg1-1&stamp=1474498847>.

Pick up date from SOURCE_DATE_EPOCH, for reproducible builds

---

code/client/snd_wavelet.c
code/ui/ui_main.c

gcc 6 warns about some array underflows while compiling ioquake3. Please see the individual commit messages for more details.

Fix array underflow compiler warnings

---

code/botlib/l_precomp.c
code/game/bg_lib.c
code/qcommon/md5.c
code/qcommon/vm_interpreted.c
code/renderergl1/tr_surface.c
code/ui/ui_shared.c

gcc 6 with -Wall -Wextra warns:
code/botlib/l_precomp.c: In function ‘PC_NameHash’:
code/botlib/l_precomp.c:551:2: warning: ‘register’ is not at beginning of declaration [-Wold-style-declaration]
int register hash, i;
^~~

Don't use mostly obsolete 'register' keyword

---

code/client/snd_mem.c

reset samplefrac to 8-bits (0...255) in every loop to prevent overflow.
fixing issue #106

reset samplefrac to 8-bits, to prevent overflow

---

code/sdl/sdl_glimp.c

The test string is missing the initial "GL_" so it is always failing the test even when supported on newer hardware.
This was caused by the original 'string compare against the ENTIRE extension string' test that was mass-converted to using proper extension-testing functioins during commit c923872ca2e5387f359c4d95c293e5900f91a36c
Should a separate test for GL_ARB_texture_env_add be added as well? No changes to the interface, the existing GL_EXT was promoted to full ARB status many years ago; I'm unsure if any video cards only advertise the ARB but not the EXT string.

Correct test for GL_EXT_texture_env_add support

---

Makefile

If [platform specific](https://cygwin.com/cgi-bin2/package-cat.cgi?file=x86_64%2Fmingw64-x86_64-binutils%2Fmingw64-x86_64-binutils-2.25.0.1.23f238d-1&grep=windres) binutils is not installed, but [generic binutils](https://cygwin.com/cgi-bin2/package-cat.cgi?file=x86_64%2Fbinutils%2Fbinutils-2.25-4&grep=windres) is installed, WINDRES equals to empty string. In this situation when make tries to call 
> $(WINDRES) bebebe
it will fail with "bebebe command not found". This commit sets default value for WINDRES for mingw platform

Makefile: using generic windres if specific one is not present in mingw platform

---

Makefile

Make FreeBSD build work closer to how FreeBSD users expect it to work:
- Obey CFLAGS -On level
- Remove shenanigan to pull CFLAGS into BASE_CFLAGS
- Add COMPILE_ARCH conversion  i386 → x86

Freebsd build

---

Makefile

Steps to reproduce:
git init
git submodule add -b master git://github.com/ioquake/ioq3.git
cd ioq3
make USE_GIT=1
I just tried this build, and it still shows the correct git hash at the top of the console.

Fix build when cloned as submodule

---

code/qcommon/files.c
code/qcommon/q_shared.h
code/qcommon/qcommon.h
code/sys/sys_unix.c
code/sys/sys_win32.c

The current implementation of `Sys_SteamPath` doesn't call `RegCloseKey` to close the registry handle. This is now fixed. 
In addition, GOG installs of Quake 3 are now detected in the same way Steam installs are. This resolves #157.

Update install path detection

---

code/qcommon/files.c

- Paths to search for mods are now specified in an array
- Mods can now consist solely of ".pk3dir" folders and still be
considered valid
- The function now has a consistent style

Improve FS_GetModList

---

code/qcommon/files.c

Don't include (mission)pak_checksums in standalone build

---

code/cgame/cg_newdraw.c

MISSIONPACK define is already required for this file or else it triggers an #error at the top of the file - removing redundant test that will never occur.

Redundant #ifndef MISSIONPACK block

---

code/cgame/cg_main.c

The previous cleanups added a few redundant 'close then immediately open the same ifdef' blocks, this pull request removes them.

...too much MISSIONPACK ifdeffery.

---

code/qcommon/vm.c
code/qcommon/vm_interpreted.c
code/qcommon/vm_local.h
code/qcommon/vm_x86.c

Constructions like (dataMask & ~3) was used to protect against out-of-bound load/store when address is 4-byte closer to dataMask.
But at the same time it effectively cut low address bits for ALL load/store operations which is totally wrong in terms of conformance to ALLOWED (i.e. generated by q3lcc from C sources) low-level operations like packed binary data parsing

Allow unaligned load/store in QVM interpreter/x86 compiler

---

Makefile
autoupdater-readme.txt
code/autoupdater/autoupdater.c
code/autoupdater/sha256.c
code/autoupdater/sha256.h
code/sys/sys_autoupdater.c
code/sys/sys_main.c

This is my first attempt at writing an autoupdater for ioq3.
I wanted to go in a direction like iOS apps or Google Chrome, etc, which quietly update as necessary and never bother you about it. An upside to this approach, beyond not bothering the user, is that we never have to get bogged down in GUI code.
The gist is that the game launches the autoupdater on startup and never thinks about it again; the autoupdater does its work in the background, waits for the game to exit and replaces updated files and then quietly terminates. If something goes wrong, the autoupdater will rollback any changes it made and try to pick up where it left off next time.
This is still work in progress; there are several things that need improvement, plus a port to Windows, etc. I just wanted to get the ball …

Initial shot at writing an ioquake3 autoupdater.

---

README.md
code/client/cl_console.c
code/client/cl_keys.c
code/qcommon/common.c
code/qcommon/qcommon.h
code/sys/con_tty.c

Add `con_autoclear` cvar from ET to allow disabling clearing client console input text when console is closed.
Add `con_autochat` cvar from Spearmint to allow disabling sending console input text as chat when there isn't a leading slash. Instead it's processed as a command.
Both cvars default to 1; using the original Q3 behavior.
I believe it's ready to be merged. Do other maintainers have an opinion on adding these?

Add con_autochat and con_autoclear cvars

---

code/sys/sys_main.c

This change prevents an intermittent crash issue I encountered (#257) with the Windows dedicated server builds, where a Com_Printf call would trigger a crash due to the console system not being initialized.
The crash traced to main->Com_Init->Com_Printf->Sys_Print->CON_Print->CON_Hide->CON_Show->WriteConsoleOutput, where WriteConsoleOutput was passed an unitialized qconsole_hout handle.
I've only very lightly tested this fix, but it should be at least safe for non-dedicated builds, since there CON_Init is only a stub so moving it doesn't make a functional difference.

Move CON_Init ahead of Com_Init to avoid Windows dedicated server crash

---

code/client/cl_main.c
code/q3_ui/ui_servers2.c
code/ui/ui_main.c

[Pull request instead of just pushing to master in case people have issues with how I'm fixing and sort of breaking UI VM compatibility.]
This commit fixes the vanilla Q3 UI VMs not displaying a server list
when id Software's master server is down.
Originally master 0 for the globalservers command was Internet and
master 1 was MPlayer (defunct). In 2008 ioquake3 changed it so that
master 0 to 4 were five separate master servers with no affect on
original Quake3/Team Arena UI VMs; they continued to get the server
list from master.quake3arena.com.
id Software's master server (master.quake3arena.com) goes down
occasionally. Using ioq3's UI VM additional master servers can be
accessed but players using the original UI VMs are unable to get a
server list.
In order to fix the original UI VMs in …

Make 'globalservers 0' fetch all masters

---

code/client/cl_curl.c

A malicious server could abuse dangerous protocols such as gopher:// to,
for instance, send mail via SMTP.

Only allow safe protocols for cURL downloads.

---

code/sdl/sdl_input.c

It is assumed that user can't resize window on fullscreen. This fixes screen looping bug

ignore window resize event on fullscreen

---

code/qcommon/common.c
code/qcommon/q_math.c

The use of signed types in these expressions lead to overflow, hence undefined behaviour. The "sum" aggregator in Com_TouchMemory isn't even used (and presumbably just exists to inhibit optimizations from removing the memory access).

[qcommon] Use unsigned types where wrapping arithmetic is intended

---

code/botlib/be_aas_def.h

The array is part of a structure and should have a fixed size that does not depend on inclusion order.
The use of the conditional `MAX_PATH` macro is causing real havoc with the integration of the BSPC code, which defines that macro for its own uses, independent of this `aas_t` structure.
Was there ever any value in making the `aas_t` field size dependent on an external macro like that?
Credits to @TTimo, who suggested a modification of this kind.

[botlib/be_aas_def.h] Change array size from MAX_PATH to MAX_QPATH

---

Makefile

A race condition can happen when running "make all" with parallel jobs.
The issue is that the build directory can be created by another
concurrent job between the moment it was detected as missing and the
moment mkdir is called (which fails if the directory already exists).
This fixes the problem by always using `mkdir -p` which doesn't fail if
the directory already exists.

Fix a race condition in the makedirs target

---

Makefile

OpenBSD's sed (and possibly other platforms') interprets `\r` as a
literal `r` rather than a carriage return, which leads to all `r`
letters being stripped from the shaders' source.
This fixes the issue by using the POSIX-compliant `tr -d '\r'` to remove
carriage returns.
Thanks to @ryan-sg for reporting the issue

Fix shader corruption on OpenBSD

---

misc/linux/server_compile.sh

(As requested by @TimeDoctor)
I tried to split things up into multiple PRs, but it really wasn't possible to get "clean" diffs that were independent of each other.  If you only want a subset of changes, let me know which ones and I can whip up a reduced changeset.
In no particular order:
* Use `set -e`, because it prevents accidents, and means we can avoid
lengthy &&-joined command chains.
* Override defaults by setting env vars; this means people don't have to
edit the script to change things.
* Use an unpredictable and safely-created tmpdir for building; ain't nobody
wants to cleanup from a tmpdir race condition attack.
* Switch to passing `-j` to `make`, by default; any reasonably recent version
of `make` will happily interpret that as "use as many cores as we have".
* Test for the …

Improvements to the linux build script

---

code/qcommon/common.c

These entities do not require external linkage.

[qcommon] Make several variables and function static.

---

code/client/cl_curl.c

Allows higher download throughput (from ~2 MB/s to ~60 MB/s at 120FPS)
This has no effect for curl versions older than 7.53.0 (for which the
buffer can only be shrunk below 16k)

Maximize cURL buffer size

---

code/client/cl_avi.c
code/client/snd_dma.c
code/client/snd_local.h
code/client/snd_mix.c
code/sdl/sdl_snd.c

Fixes missing audio when playing on Windows with SDL 2.0.7, which started
using WASAPI, which demands floating point audio.

Support SDL audio devices that require float32 samples.

---

Makefile
code/client/snd_altivec.c
code/client/snd_local.h
code/client/snd_mix.c
code/renderergl1/tr_altivec.c
code/renderergl1/tr_local.h
code/renderergl1/tr_shade.c
code/renderergl1/tr_shade_calc.c
code/renderergl1/tr_surface.c
code/renderergl2/tr_shade.c
code/renderergl2/tr_shade_calc.c
code/renderergl2/tr_surface.c

This means we can use GCC's `-maltivec` on just these files, which are chosen at runtime if the CPU supports Altivec, and compile the rest without it, making a single binary that has both Altivec optimizations but can still work on G3.
Unlike #367, this includes the Makefile changes to avoid `-maltivec` for the rest of ioquake3, and compiles successfully on powerpc.
Fixes #181.
As of e4677a5:
[x] Compiles successfully on a Linux powerpc system (Debian unstable)
[ ] Runs successfully on Altivec-capable powerpc (Mac G4, Mac G5, Playstation 3 or similar) - I can test this on a G4 Powerbook at some point
[ ] Runs successfully on non-Altivec-capable powerpc (Mac G3, Freescale e5500 or similar) - I don't have the hardware for this, perhaps @casey-ac or @rcgordon could test this configuration?

[untested] Move all the Altivec code to its own source files

---

Makefile

This is one of the de facto standard interfaces used in Linux
distributions for cross-compilation (alongside overriding CC and
similar variables), and in particular is used in Debian and its
derivatives.

Allow pkg-config binary to be overridden with PKG_CONFIG

---

code/client/cl_main.c

A small addition to CL_RefPrintf to add support for the PRINT_ERROR print level. Currently nothing is printed to the console.

Fixed PRINT_ERROR print level missing from CL_RefPrintf.

---

code/tools/lcc/cpp/cpp.c

Allow to override `__DATE__` and `__TIME__` with `SOURCE_DATE_EPOCH`
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
This behavior is what gcc already does.
Without this patch, `qagame.qvm` would differ between builds.
This PR was done while working on reproducible builds for openSUSE.

q3rcc: Allow to override build date

---

code/curl-7.54.0/include/curl/curlbuild.h

Fixed build by MCST lcc compiler on MCST Elbrus 2000 architecture when using USE_CURL=1 option.
e2k (Elbrus 2000) - this is VLIW/EPIC architecture, like Intel Itanium architecture.
About this architecture:
- https://en.wikipedia.org/wiki/Elbrus_2000

E2K: fixed build by MCST lcc compiler when using USE_CURL=1 option

---

code/renderergl1/tr_init.c
code/renderergl2/tr_init.c

This improves visual quality without a noticeable performance loss, especially on maps that use textures with high-frequency details such as q3dm1.

Use `r_texturemode GL_LINEAR_MIPMAP_LINEAR` by default

---

code/sdl/sdl_glimp.c

There is no need for a tentative definition in this case. By providing
an explicit initializer, the resulting definition has the same effect
as before, but is no longer tentative. This avoids easy errors
resulting from multiple tentative definitions in different translation
units. (Previous compilers permitted those common errors, but GCC 10
rejects them by default.)

[sdl] Turn tentative definition into actual definition.

---

code/asm/vm_x86_64.asm

Not all non-volatile registers were actually saved and restored, leading to a few registers being trashed after calling the vm instructions.
All non-volatile registers have been added.

Windows: qvmcall64 non volatile register corruption on x64

---

code/asm/vm_x86_64.asm

qvmcall64 has its own custom calling convention due to pushing all non-volatile registers to the stack. The game uses set/longjmp which on Windows uses "RtlUnwindEx" to unwind the callstack. qvmcall64 cannot be unwound by default due to the custom calling convention. To allow unwinding, we need to add custom SEH unwind data to the function.
This fix is only needed when the qvmcall64 function is used which typically only happens when you compile the project with msvc.

Windows: Allow unwinding of qvmcall64 call-stub

---

Makefile

Fix for #526.
ranlib on older macOS errors because of arm64 arch in code/libs/macosx/libSDL2main.a. Use lipo to extract the library for the specific arch that is being linked.

Fix compiling on older macOS

---

code/client/snd_mix.c

When using a non-default sound configuration (such as 6 channels), after
a long time (about 4.5hours for 6 channels at 22050 Hz) an overflow will
occur in `S_TransferPaintBuffer`, causing an out of bounds write into
the dma buffer.
The problematic line is:
```
out_idx = (s_paintedtime * dma.channels) % dma.samples;
```
With `s_paintedtime` large enough, the result of the multiplication will
overflow to a negative number (since `s_paintedtime` is signed), and the
index into the output buffer will be negative.

Fix memory corruption in S_TransferPaintBuffer

---

code/qcommon/vm_x86.c

Fixes https://github.com/ioquake/ioq3/issues/538 based on @zturtleman's example code (which just worked perfectly as it was), thank you a lot (and the other contributers @tomkidd and @DanielGibson for elaborating and discussing the issue)!
Tested in VS2019 only, but I don't see how this could conflict with anything else, as these predefinitions are made for this.
From https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-160:
`_M_IX86`: Defined as the integer literal value 600 for compilations that target x86 processors. This macro isn't defined for x64 or ARM compilation targets.
`_M_X64`: Defined as the integer literal value 100 for compilations that target x64 processors. Otherwise, undefined.

vm_x86.c: Add `defined(_M_IX86) || defined(_M_X64)` (fix for VS2019)

---

code/client/cl_main.c
code/qcommon/q_shared.h
code/sys/sys_local.h
code/sys/sys_main.c
code/sys/sys_osx.m
make-macosx-app.sh
misc/nsis/ioquake3.nsi.in
misc/setup/ioquake3.desktop

This lets the user click a link in a web browser to very easily join a Quake 3 multiplayer game. As browser-based matchmaking websites become more popular, this makes it a lot more convenient and simple to play Quake 3 with others.
The links have the following URI format: `quake3://connect/example.com:27950`. The format has been designed to be flexible to allow more types of links in the future and avoiding having to make a breaking change. At the moment, `connect` is the only supported command.
Just imagine if each of the servers on the page https://www.quakeservers.net/quake3/servers/ had a button next to it that said <kbd>Join Server</kbd>. I think that would make it easier to both attract new players, and keep them engaged in the longer term.
When you click a link, you will see a …

Protocol handler

---

code/server/sv_client.c

Having a reliableAcknowledge of 0x7FFFFFFF causes a massive loop to be executed in SV_UpdateServerCommandsToClient due to the + 1 overflow.
Original find: https://github.com/callofduty4x/CoD4x_Server/pull/336
on a VPN, so idc about IP

Fix bad client reliableAcknowledge DOS exploit

---

code/sdl/sdl_input.c
code/sys/sys_local.h
code/sys/sys_main.c
code/sys/sys_osx.m

Use SDL's SDL_DROPFILE event to receive URLs to handle on macOS for URL protocol schemes listed in the AppBundle Info.plist. This also handles URLs while the game is running (connect to new server) instead of nothing happening when clicking a link while the game is running.
This fixes the macOS client and server being completely unusable when run from a terminal. They blocked forever in `[NSApp run];` which was called by Sys_InitProtocolHandler(). `applicationDidFinishLaunching` was never called to exit the NSApp run loop.
I didn't manage to find a way to know whether it was run from terminal or launch services (?) to not enter `[NSApp run]` or another way to allow bailing out of `[NSApp run]`. So use the SDL event instead.

Use SDL event for protocol handler on macOS

---

code/sys/sys_unix.c
code/sys/sys_win32.c

The mod list on Windows would search the root of the drive if fs_basepath, fs_homepath, fs_steampath, or fs_gogpath are blank ("") (which is usually the case).
The issue is in the low-level Sys_ListFiles() but it only affects the mod menu, on Windows. It cannot be abused by console commands to list system files outside of the virtual filesystem.
There are more technical details in the commit message.

Don't list mod directories at Windows drive root

---

misc/setup/org.ioquake3.IOQuake3.metainfo.xml

This PR adds [AppStream](https://www.freedesktop.org/software/appstream/docs/) metadata for ioquake3 created as a part of packaging ioquake3 into [Flatpak](https://flatpak.org) for Linux / Steam Deck.
I have decided not to add this file into the install scripts and let users/package maintainers install it manually only if they want to. (I am also not sure how compatible it would be with the Loki Setup install scripts and/or other operating systems like Solaris.)
Feel free to review and merge and if you have any question, please ask. Thanks!

Add AppStream metadata

---

misc/setup/org.ioquake3.ioquake3.metainfo.xml

Specify license as GPL-2.0-or-later. It's meant to be an SPDX identifier and [SPDX doesn't have GPL-2.0](https://spdx.github.io/spdx-spec/v2.3/SPDX-license-list/); Flathub displays it as GPL-2.0-only.
Mark it as realistic violence instead of fantasy based on [OARS generator](https://hughsie.github.io/oars/generate.html): "For example, this would include a user shooting a gun at a human characters." ESRB also lists Quake III Arena as violence, not fantasy violence.
Mark it as intense social-audio because unmoderated voice chat is supported.

Improve AppStream metainfo

---

Makefile

The QVM interpreter works on all platforms. If building QVMs is an issue, that should probably be handled separate from whether there is a QVM JIT compiler.
This enables building QVMs by default on Linux arm64.

Build QVMs even if there is no QVM JIT

---

code/renderergl2/tr_backend.c
code/renderergl2/tr_local.h

OpenGL2: Fix cg_viewsize < 100 and fix r_clear 1

---

code/renderergl2/tr_fbo.c

Fix r_ext_framebuffer_multisample > 0 causing the screen to always be solid black when using AMD Windows driver.
The AMD Windows driver requires binding renderbuffer for it to be valid. The OpenGL2 renderer uses GL_EXT_direct_state_access that shouldn't require this. It would be required for Core and GL_ARB_direct_state_access. It seems like a driver bug.
Reported on the [ioquake3 forum](https://discourse.ioquake.org/t/black-screen-in-quake-3-when-using-multi-sampling-ond-amd-graphics-card/1893).

OpenGL2: Fix FB-MSAA on AMD Windows driver

---

code/renderergl2/tr_backend.c

Generating cubemaps set backEnd.viewParms.isMirror = qtrue while the loading screen said 'loading... maps/q3dm1.bsp' and it just stayed like that until done loading (no additional messages or item icons) because all 2D drawing was culled due to flipped culling for isMirror.
This was noticed because a [recent commit](https://github.com/ioquake/ioq3/commit/a81df34905fab89ad478237c269fc26bb1262489) fixed RB_ShowImages() to be drawn to the screen instead of draw into renderFbo and never blit to the screen. Now the loading screen draws over it as expected.

OpenGL2: Fix updating the loading screen with r_cubeMapping 1

---

code/renderergl2/tr_bsp.c
code/renderergl2/tr_shader.c

Fix q3map2 lightstyles on World of Padman's wop_trashmap (Fixes https://github.com/ioquake/ioq3/issues/622 and two other issues).
Fix skipping the next shader line after q3gl2_sun shader keyword if it doesn't have the "optional" arguments.

OpenGL2: Fix q3map2 lightstyles and parsing q3gl2_sun shader keyword

---

code/tools/lcc/cpp/lex.c
code/tools/lcc/cpp/unix.c
code/tools/lcc/lburg/gram.c
code/tools/lcc/lburg/gram.y
code/tools/lcc/lburg/lburg.c

On non-Windows, compiling QVM tools failed if [dagcheck.md](https://github.com/ioquake/ioq3/blob/main/code/tools/lcc/src/dagcheck.md) had CRLF line endings and compiling QVMs failed if game source had CRLF line endings.
Also made Windows open the files as binary (no automatic CRLF to LF) so it behaves the same as on non-Windows.
----
If code/tools/lcc/src/dagcheck.md has CRLF line endings, fails to compile QVM tools.
```
LBURG code/tools/lcc/src/dagcheck.md
line 1: invalid character `%'
line 1: invalid character `{'
line 1: invalid character `\015'
line 2: invalid character `#'
line 2: syntax error
line 2: invalid character `\015'
line 3: syntax error
line 3: invalid character `;'
line 3: invalid character `\015'
...
```
If QVM tools compiled but game source has CRLF line endings, it …

Fix building QVMs on Linux with Windows line endings

---

code/renderergl2/tr_fbo.c

Using r_drawSunRays 1, r_hdr 0, cg_viewsize 50 caused the sun rays to only draw properly in the bottom right quarter of the world viewport.
The scissor rectangle for the world viewport was applied to the first FBO_FastBlit() in RB_SunRays().
Set glScissor() in FBO_FastBlit() as it's done in FBO_Blit() and FBO_BlitFromTexture(). Sun rays probably worked correctly with r_hdr 1 because the blit for HDR changed the scissor state.
Fixes #305.

OpenGL2: Fix sun rays being affected by the viewport size

---

code/renderergl2/tr_bsp.c
code/renderergl2/tr_local.h
code/renderergl2/tr_shader.c

- Fix the texcoord range for external lightmaps in a shader with an internal lightmap to be 0.0 to 1.0. (With texture repeating it would wrap around and read correctly but clampMap or tcMods might not of worked.)
- Fix merged lightmaps using tcGen environment. (Fixes  #636.)
- Only apply the hack to fix _tcMod transform on internal merged lightmaps_ to tcGen lightmap.

OpenGL2: Fix merged lightmaps using tcGen environment

---

code/renderergl2/tr_backend.c

When r_ext_framebuffer_multisample > 0 was used, flares behind the mirror in q3tourney6 were incorrectly visible. This was because it checks scene depth in the depth prepass which only drew opaque surfaces. It also needs to contain depth for mirror/portal surfaces.
Fixes #121.

OpenGL2: Fix flares behind mirror being visible

---

code/sys/sys_win32.c

Newer mingw-w64 changed default Windows version compatibility. Need to specify older behavior for EnumProcesses() to avoid "missing K32EnumProcesses()" runtime error.
Reported at [the ioquake3 forum](https://discourse.ioquake.org/t/how-to-run-ioquake3-on-windows-me-and-xp/1860/4).

Fix running on Windows XP

---

.github/workflows/build.yml

The GitHub Actions summary page had the following warning:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Fix GitHub Actions CI deprecation warnings

---

code/renderergl2/tr_backend.c
code/renderergl2/tr_image.c
code/renderergl2/tr_postprocess.c
code/renderergl2/tr_postprocess.h

Don't draw the world scene to a separate FBO from the rest of the screen.
This fixes the world scene having HOM instead of seeing through to the previously drawn content. World of Padman uses this to have a separate 3D scene for the sky and world in wop_padship for dynamic skybox.
This also makes r_ext_framebuffer_multisample apply to HUD models instead of depending on r_ext_multisample (which doesn't work on Linux with some Intel graphics).

OpenGL2: Don't mix drawing to default framebuffer and FBO

---

code/renderergl1/tr_sky.c

Fix six image skybox having a black border around the sides of the sky when using OpenGL 1.1 (using CL_CLAMP instead of GL_CLAMP_TO_EDGE).
It's technically visible in q3dm10 but it's more obvious in Team Arena maps such as mpteam6.
Fixes #656.

opengl1: Fix skybox in OpenGL 1.1

---

code/autoupdater/autoupdater.c
code/sys/sys_unix.c

usleep(3) was declared obsolete in POSIX.1-2001 and removed in POSIX.1-2008 and nanosleep(2) was recommended to be used instead.

Use nanosleep(2) instead of usleep(3)

---

Makefile

In the Makefile at line 1686, TOOLS_CC is used, which defined to only use gcc (at line 1549). FreeBSD now defaults to Clang, so the build breaks there. This patch addresses this.

Makefile: fix compilation on FreeBSD

---

.github/workflows/build.yml

macOS 11 runner image is scheduled to be removed next month. [GitHub notice](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/)

Update macOS version for GitHub CI

---

README.md
code/client/cl_avi.c
code/renderergl2/tr_backend.c
code/renderergl2/tr_bsp.c
code/renderergl2/tr_cmds.c
code/renderergl2/tr_extensions.c
code/renderergl2/tr_flares.c
code/renderergl2/tr_glsl.c
code/renderergl2/tr_image.c
code/renderergl2/tr_init.c
code/renderergl2/tr_local.h
code/renderergl2/tr_mesh.c
code/renderergl2/tr_model.c
code/renderergl2/tr_postprocess.c
code/renderergl2/tr_shade.c
code/renderergl2/tr_vbo.c
code/sdl/sdl_glimp.c
opengl2-readme.md

This adds support for running the OpenGL2 renderer using the OpenGL ES 2 and 3 APIs.
It doesn't have framebuffer object support yet; used by many features such as auto-exposure/HDR, SSAO, and sun shadows.
I think this ran at 5 FPS on the Raspberry Pi 3B when I tested essentially these changes in 2019. Though I think the issue is how the OpenGL2 renderer operates rather than the ES API usage.
There is nothing actually broken about this OpenGL ES 2 port—just missing features and room for better performance—so it could be merged.

OpenGL2: Add support for OpenGL ES 2

---

README.md
code/renderercommon/qgl.h
code/renderergl2/glsl/depthblur_fp.glsl
code/renderergl2/glsl/ssao_fp.glsl
code/renderergl2/tr_extensions.c
code/renderergl2/tr_init.c
code/sdl/sdl_glimp.c
opengl2-readme.md

This fixes WebGL and adds a list of OpenGL context types to try. It will fallback to GLES2 if OpenGL fails (and vice-versa as it already did).

OpenGL2: Fix WebGL and add fallback to GLES2

---

Makefile
code/qcommon/q_platform.h
code/sdl/sdl_glimp.c
code/sys/sys_main.c

This is a minimal emscripten port that will build and run. It supports the OpenGL2 renderer using WebGL 1.0 and 2.0. It uses the generated html file from emscripten and "--preload-file" to merge all pk3s into a single file that emscripten loads as a VFS.
There is a lot of room to improve different aspects like pk3 loading, html integration, loading game logic from .wasm, and build flags. (Which is to say this is not necessarily better or more complete than the [several](https://github.com/inolen/quakejs) [other](https://github.com/klaussilveira/ioquake3.js) [ports](https://github.com/ioquake/ioq3/pull/658) using emscripten.)
1. Create "baseq3" directory in the same directory as the Makefile.
2. Copy pak[0-8].pk3 into the created "baseq3" directory.
3. Run `/path/to/emsdk.sh` to add emcc …

Add minimal emscripten support

---

code/sdl/sdl_glimp.c

If getting the display index of the existing window fails, fallback to the default display size instead of falling back to 640x480.
emscripten r_mode -2 worked on window creation but vid_restart fellback to 640x480.

Fix web client vid_restart with r_mode -2

---

code/qcommon/common.c
code/renderergl2/tr_init.c

Default com_maxfps to 0 under Emscripten. Under Emscripten the browser handles throttling the frame rate. Manual framerate throttling interacts poorly with Emscripten's browser-driven event loop.

Fix framerate throttling in Emscripten builds

---

code/renderergl2/glsl/shadowmask_fp.glsl

Don't project sun shadows (r_forceSun 1) on to view depth equal to 1.0 (nothing drawn or skybox). This caused a full second shadow of the entire level in tr.screenShadowImage. It would move as the camera far plane changed and rotate/stretch strangely as the camera view changed.
It was visible in-game on lightmapped transparent surfaces facing the skybox and happen to overlap the extra shadow of the level.
This affected the glass in wop_padship's underwater room.
----
World of Padman (engine fork) screenshots of wop_padship showing the issue:
"oh there's the problem, there is a phantom ship."
(The glass should all be the same brightness.)
ioquake3 with q3dm1 map:
(All maps had a second shadow in the shadowmap image but I don't know of cases it caused issues.)

OpenGL2: Don't project sun shadows onto nothing

---

code/renderergl2/glsl/shadowmask_fp.glsl

This fixes #680 on more hardware as per https://github.com/PadWorld-Entertainment/worldofpadman/issues/266.
Increase the range for clamping the screen shadow depth to 1.0 (nothing drawn). Old epsilon ~0.00000006, new 0.001. This fixes it on another computer.

OpenGL2: Fix still projecting sun shadows onto nothing

---

code/qcommon/files.c
code/sys/sys_win32.c

This adds better directions for what to do when Quake 3 or Team Arena pk3 files are missing. (Idea inspired by the [org.ioquake3.ioquake3 Flatpak's message](https://github.com/flathub/org.ioquake3.ioquake3/blob/63244a01f9a0e532922f472d2db6e02e80692fc7/ioquake3#L6-L20).)
The files to copy is set based on what files are missing and either a range ("pak3.pk3" through "pak8.pk3") or a list of a pk3s ("pak0.pk3", "pak7.pk3", and "pak8.pk3").
I tested it displayed okay on Linux (zenity), Windows, and macOS. I only took screenshots from Linux.
The error message contains a URL so I made the Windows fatal error dialog "copy to clipboard" option include the error message like Unix-like platform's crashlog.txt.
Existing message when missing all Quake 3 pk3 files:
New message:
Steam is (probably …

Add better directions/error for missing Quake 3 / Team Arena pk3 files

---

code/qcommon/files.c
code/sys/sys_unix.c

Use XDG_DATA_HOME for Flatpak so that fs_homepath is accessible without special permissions/handling. This changes the home path for Flatpak from ~/.q3a/ to ~/.var/app/org.ioquake3.ioquake3/data/q3a/. (This is the recommended handling for Flatpak applications.)
In the missing baseq3 pk3 error for Flatpak, tell users to copy pk3 files to fs_homepath as fs_basepath is not user writable. (Displaying fs_basepath was introduced today in #634.)

Make Flatpak use XDG_DATA_HOME and tell users to copy missing pk3s there

---

code/botlib/be_aas_file.c

FS_Seek() doesn't always return 0 on success. If the file in a pk3 file it returns the seek offset. This change doesn't fix any known AAS files.
I found the issue when reviewing https://github.com/ioquake/ioq3/issues/690.

Fix reading non-sequential lumps in AAS files in pk3 files

---

code/qcommon/files.c

Link to https://buy.ioquake3.org instead of https://ioquake3.org/extras/patch-data/.

Change URL for missing files dialog

---

code/server/sv_client.c
code/server/sv_main.c

This fixes an issue where SV_DropClient() would get called twice on the same client if the later gets kicked and has too many reliable commands right while sending a server command in SV_DropClient().
For example when kicking a client, SV_DropClient() gets called and sends server commands (print + disconnect). If the kicked client has too many reliable commands, SV_AddServerCommand() would call SV_DropClient() again on the same client.
This bug can occur as follow:
* SV_CheckTimeouts() is called
* SV_DropClient() gets called on a client that timed out
* SV_SendServerCommand() gets called to print stuff
* SV_AddServerCommand() is called on the client being dropped
* SV_DropClient() is called because it's exactly the 513th command
* Print stuff, call VM stuff, send "disconnect", reset the …

Prevent SV_DropClient() from being called recursively

---

.github/workflows/build.yml

macos-12 is outdated, this commit simply updates the build.yml file to attempt to use macos-13
see https://github.com/actions/runner-images/issues/10721 for more details on this change.

Update build.yml to macos-13

---

code/cgame/cg_draw.c
code/cgame/cg_local.h

For some time glibc has defined a macro with the same name in `limits.h`. Avoid the warning by renaming our macro. If not, we would get following warnings:
```
In file included from code/cgame/cg_weapons.c:24:
code/cgame/cg_local.h:66:9: warning: ‘CHAR_WIDTH’ redefined
66 | #define CHAR_WIDTH                      32
|         ^~~~~~~~~~
In file included from code/cgame/../qcommon/q_shared.h:170,
from code/cgame/cg_local.h:23:
/usr/lib/gcc/ppc64le-redhat-linux/15/include/limits.h:165:10: note: this is the location of the previous definition
165 | # define CHAR_WIDTH __SCHAR_WIDTH__
|          ^~~~~~~~~~
```

Rename CHAR_WIDTH to CHARACTER_WIDTH

---

.github/workflows/build.yml

Ubuntu 20.04 was deprecated: https://github.com/actions/runner-images/issues/11101

Update build.yml with ubuntu-24.04

---

code/renderergl2/tr_init.c
code/renderergl2/tr_local.h
code/renderergl2/tr_surface.c

The VAO surface cache uses glBufferSubData and triggers a very slow
path in some GLES implementations. Specifically I have observed 10x
frame times under Emscripten with ANGLE/Metal on macOS and with Mali
on Android.
Supersedes https://github.com/ioquake/ioq3/pull/678, implemented the recommendations from https://github.com/ioquake/ioq3/pull/678#issuecomment-2216812337. I personally don't really know what I'm doing.

OpenGL2: Disable the VAO cache by default

---

.github/workflows/build.yml
code/tools/asm/cmdlib.c
code/tools/asm/q3asm.c
code/tools/lcc/etc/lcc.c
code/tools/lcc/src/output.c

GitHub is ending support for the windows-2019 runner image and windows-2022 will be the minimum supported version by the end of June, 2025. We need to update before this date. More information about this change is here: https://github.com/actions/runner-images/issues/12045

Update build.yml to replace deprecated windows-2019 with windows-2022

---

Makefile

Client compile flags are used for server unzip.c and ioapi.c since 124000104e2b9d13d6a416e4c8b2b746436150a8. This corrects it to use server compile flags.

Fix server compile flags for unzip.c and ioapi.c

---

code/cgame/cg_draw.c
code/cgame/cg_local.h

Undefine CHAR_WIDTH from libc instead of renaming CGame's CHAR_WIDTH.
Renaming CHAR_WIDTH to CHARACTER_WIDTH make it's inconsistent with CHAR_HEIGHT. It would also require renaming it in mods/derivatives. There isn't any meaningful value from doing this.
Having access to C23 CHAR_WIDTH in CGame to know char type is 8 bits isn't likely to be useful.

Restore CHAR_WIDTH

---

cmake/compilers/gnu.cmake

The README says that it can be changed, but it was hard-coded here.

cmake: Don't override CMAKE_INSTALL_PREFIX if set by user

---

code/qcommon/q_platform.h
code/qcommon/vm.c

* qcommon: Assume that unknown architectures don't have a JIT for QVMs
We need specific code for any architecture that does have a JIT, so we
can safely assume that any other architecture does not.
* qcommon: Reverse the sense of NO_VM_COMPILED
Instead of defining NO_VM_COMPILED on the unlimited number of CPU
architectures where we don't have a JIT for QVM bytecode, define
HAVE_VM_COMPILED on the finite number of architectures where we do
(x86, PowerPC, Sparc or 32-bit ARM).
---
Alternative to #788, please merge whichever one you like better.

Treat architectures that *do* have a JIT as unusual

---

code/botlib/botlib.h
code/client/cl_main.c
code/client/cl_parse.c
code/client/cl_ui.c
code/game/ai_main.c
code/qcommon/common.c
code/qcommon/files.c
code/qcommon/md5.c
code/qcommon/q_shared.h
code/qcommon/qcommon.h
code/server/sv_ccmds.c
code/server/sv_client.c
code/sys/sys_unix.c
code/sys/sys_win32.c

For reasons I was looking at how all the various search paths were resolved in the file system code. What I found was quite a lot of repetition and duplication. In fairness it's completely understandable how this has happened, as we've incrementally added support for sourcing data from Steam, GoG, etc. where each addition has no doubt seemed small, but then cumulatively it's become quite hard to read and introduced some scope for obscuring bugs since a fix/change to one bit of code requires that the change is copied throughout. (As an example FS_GetModList doesn't seem to check the macOS .app or Microsoft Store paths, and it probably should.)
In order to address this I've added a global fs_pathVars array that lists all the cvars from which we derive data, in order, which is then looped …

Reduce duplication in FS path search code

---

.github/FUNDING.yml
README.md

I'm stepping away from ioquake3 due to changes in my software priorities. I will continue my Quake 3 projects separately.
Adding a former maintainers section to the README seems like a good way to reflect this. I'd prefer to remove my funding link.

Note former maintainers, remove my funding link

---

code/qcommon/msg.c

Currently for example, if `bit` is 65536 and `maxsize` is 8192, then `cursize` would be `(65536 >> 3) + 1` = 8193, after the maximum size. (`Netchan_Transmit` would drop an error when trying to send more than 49152 bytes)
This commit simply sets the overflow flag when the number of bits written reaches the maximum size.
I didn't find better solutions. I first found this one solution:
```cpp
msg->cursize = (msg->bit>>3);
if (msg->bit & 7)
msg->cursize++;
```
However this change must be made in `MSG_ReadBits` as well, which would break compatibility with existing clients.

Set the overflow flag when the number of bits written reaches the maximum size
