Makefile, code/qcommon/q_platform.h
Add support for Aarch64, the 64-bit ARM architecture.
=> Add support for Aarch64 (ARM64)

code/sdl/sdl_glimp.c, code/sdl/sdl_input.c, code/sdl/sdl_snd.c
see https://wiki.libsdl.org/SDL_Init
=> SDL_Init zero check

code/sdl/sdl_input.c
See https://wiki.libsdl.org/SDL_SetWindowGrab
=> SDL_FALSE/TRUE for SDL_SetWindowGrab

code/sdl/sdl_gamma.c
See https://wiki.libsdl.org/SDL_SetWindowGammaRamp
=> SDL_SetWindowGammaRamp check

code/sdl/sdl_glimp.c
See https://wiki.libsdl.org/SDL_GetWindowDisplayIndex
=> SDL_GetWindowDisplayIndex check

code/sdl/sdl_glimp.c
See https://wiki.libsdl.org/SDL_CreateWindow
=> SDL_CreateWindow NULL check

code/sdl/sdl_glimp.c
See https://wiki.libsdl.org/SDL_GetDesktopDisplayMode
=> SDL_GetWindowDisplayIndex() check2

code/sdl/sdl_glimp.c
See https://wiki.libsdl.org/SDL_GL_SetSwapInterval
=> SDL_GL_SetSwapInterval() check

code/client/cl_curl.c
See http://curl.haxx.se/libcurl/c/curl_multi_remove_handle.html
=> qcurl_multi_remove_handle check

code/client/cl_curl.c
See http://curl.haxx.se/libcurl/c/curl_easy_setopt.html
=> qcurl_easy_setopt dev warning

code/client/cl_curl.c
See http://curl.haxx.se/libcurl/c/curl_multi_cleanup.html
=> qcurl_multi_cleanup check

code/client/cl_main.c, code/qcommon/common.c, code/qcommon/qcommon.h, code/server/sv_ccmds.c
Adding a client and dedicated server command using the tell command for the client. Asuming the tell command exist in the mod.
=> sayto cmd with player name completion

Makefile, code/client/cl_cgame.c, code/client/cl_input.c, code/client/cl_main.c, code/client/cl_parse.c, code/client/client.h, code/client/snd_openal.c, code/qcommon/qcommon.h, code/server/server.h, code/server/sv_client.c, code/server/sv_init.c, code/server/sv_main.c, code/server/sv_snapshot.c
Updated #25 to fix merge issues.
=> Use Opus for VoIP [updated]

code/null/null_glimp.c
Update includes, function signatures and add missing stub function definitions.
=> [null/null_glimp.c] Fix bitrot in null impl

code/sys/con_tty.c
use tcflush POSIX function
Should fix Issue #353
=> Remove CON_FlushIn function and where STDIN needs flushing, 

CONTRIBUTING.md
Thanks to Timbo for the suggestion. This one is mostly based on the one
from Atom.
=> First swing at a CONTRIBUTING.md

code/qcommon/q_shared.c, code/qcommon/q_shared.h
Fixes https://github.com/ioquake/ioq3/issues/393
=> Prevent Q_IsColorString from asserting on negative ascii chars

code/qcommon/files.c
=> qsort cannot be called with NULL

code/botlib/l_script.c, code/game/g_utils.c, code/renderergl2/tr_backend.c
(I don't have any experience with this codebase so someone should probably review this before merging.)
=> Small fixes

code/curl-7.54.0/include/curl/curlbuild.h
enhancement of the previous patch - https://github.com/ioquake/ioq3/pull/434
=> code/curl: update ifdef condition for MCST-LCC compiler

code/renderergl1/tr_curve.c, code/renderergl2/tr_curve.c
=> More predictable mesh normals generation

code/renderergl1/tr_curve.c, code/renderergl2/tr_curve.c
The code path without PATCH_STITCHING is missing an argument for ri.Hunk_Alloc().
=> Fix compiling without PATCH_STITCHING defined

code/renderergl2/tr_flares.c
Fixes https://github.com/ioquake/ioq3/issues/687.
=> OpenGL2: Increase flare limit to match opengl1

CONTRIBUTING.md
Removed a bunch of out-of-date links and information and updated a few parts. This is still not perfect but at least it isn't so out of date.
=> Update CONTRIBUTING.md for the year 2025

README.md
didn't even mean to make a pr but whatever, here we are.
=> Update README.md to point to guides for players and sysadmins
